# Generated by Django 5.0 on 2024-01-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='yearandsection',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
