# Generated by Django 5.0 on 2024-01-28 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_yearandsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='section',
        ),
    ]
