# Generated by Django 4.2.5 on 2024-02-01 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_remove_userprofile_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='learning_style',
            field=models.CharField(blank=True, choices=[('ACT', 'Active'), ('REF', 'Reflective'), ('SNS', 'Sensing'), ('INT', 'Intuitive'), ('VIS', 'Visual'), ('VRB', 'Verbal'), ('SEQ', 'Sequential'), ('GLO', 'Global')], max_length=3),
        ),
        migrations.CreateModel(
            name='LearningStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
