# Generated by Django 4.2.5 on 2024-02-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_learning_style_learningstyle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningStyle',
        ),
    ]
