# Generated by Django 4.2.5 on 2024-02-01 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_rename_score_pretestscore_pre_score_posttestscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ILSResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_score', models.IntegerField()),
                ('ref_score', models.IntegerField()),
                ('sns_score', models.IntegerField()),
                ('int_score', models.IntegerField()),
                ('vis_score', models.IntegerField()),
                ('vrb_score', models.IntegerField()),
                ('seq_score', models.IntegerField()),
                ('glo_score', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
