# Generated by Django 4.2.5 on 2024-02-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_ilsresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ilsresult',
            old_name='act_score',
            new_name='active_reflective_score',
        ),
        migrations.RenameField(
            model_name='ilsresult',
            old_name='glo_score',
            new_name='sensing_intuitive_score',
        ),
        migrations.RenameField(
            model_name='ilsresult',
            old_name='int_score',
            new_name='sequential_global_score',
        ),
        migrations.RenameField(
            model_name='ilsresult',
            old_name='ref_score',
            new_name='visual_verbal_score',
        ),
        migrations.RemoveField(
            model_name='ilsresult',
            name='seq_score',
        ),
        migrations.RemoveField(
            model_name='ilsresult',
            name='sns_score',
        ),
        migrations.RemoveField(
            model_name='ilsresult',
            name='vis_score',
        ),
        migrations.RemoveField(
            model_name='ilsresult',
            name='vrb_score',
        ),
    ]
