# Generated by Django 4.2.5 on 2024-02-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_act_score_ilsresult_active_reflective_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretestscore',
            name='pre_score1',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pretestscore',
            name='pre_score2',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pretestscore',
            name='pre_score3',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pretestscore',
            name='pre_score4',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
