# Generated by Django 5.0 on 2024-02-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rename_post_score_posttestscore_post_score1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilsresult',
            name='active_reflective_score',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='ilsresult',
            name='sensing_intuitive_score',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='ilsresult',
            name='sequential_global_score',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='ilsresult',
            name='visual_verbal_score',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
