# Generated by Django 5.0 on 2024-04-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_ilsresult_active_reflective_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ilsresult',
            old_name='active_reflective_score',
            new_name='first',
        ),
        migrations.RenameField(
            model_name='ilsresult',
            old_name='sensing_intuitive_score',
            new_name='fourth',
        ),
        migrations.RenameField(
            model_name='ilsresult',
            old_name='sequential_global_score',
            new_name='second',
        ),
        migrations.RenameField(
            model_name='ilsresult',
            old_name='visual_verbal_score',
            new_name='third',
        ),
    ]
